djangoindia/djangoindia.org

- frontend/src/components/Goals/page.tsx
- frontend/src/components/WhatIsDjango/page.tsx
resolves (https://github.com/djangoindia/djangoindia.org/issues/28)
> fix: build error on escape unescaped entities in JSX components

- makefile
> Fixed #44 -- Added correct path for backend deps in makefile.

- backend/requirements/local.txt
- frontend/next.config.mjs
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/(core)/loading.tsx
- frontend/src/constants/common.ts
- frontend/src/constants/endpoints.ts
- frontend/src/constants/index.ts
- frontend/src/constants/schema.tsx
- frontend/src/containers/ContactUs/ContactUs.tsx
- frontend/src/containers/ContactUs/ContactUs.types.ts
- frontend/src/containers/ContactUs/SubComponents/Thanks.tsx
- frontend/src/hooks/index.ts
- frontend/src/sections/EventSection/Main.tsx
- frontend/src/sections/JoinCommunity/JoinCommunity.tsx
- frontend/src/sections/Latestupdate/LatestUpdate.tsx
- frontend/src/sections/Latestupdate/LatestUpdate.types.ts
- frontend/src/sections/Latestupdate/SubComponents/Thanks.tsx
- frontend/src/utils/fetchData.ts
- frontend/src/utils/index.ts
- frontend/tsconfig.json
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Contact Us and Newsletter API integration

- docker-compose.yml
- frontend/Dockerfile.dev
- frontend/Dockerfile.prod
- production.yml
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> fixed failing frontend with docker

- docker-compose.yml
- frontend/src/constants/common.ts
- frontend/src/constants/index.ts
- frontend/src/containers/ContactUs/ContactUs.tsx
- frontend/src/sections/Footer/Footer.tsx
- frontend/src/sections/Goals/Goals.tsx
- frontend/src/sections/Hero/Hero.tsx
- frontend/src/sections/JoinCommunity/JoinCommunity.tsx
- frontend/src/sections/Latestupdate/LatestUpdate.tsx
> Cleanup and bug fixes

- frontend/src/sections/Footer/Footer.tsx
Fixed a typo in the github link
Typo Fix
Not Needed
> Fixed GitHub link

- frontend/src/sections/Footer/Footer.tsx
- <ONE> Changed "/contactUs" to "/Contactus"
> fix: "/contactus" in the footer

- docker-compose.yml
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Added env path in postgres container.

- backend/djangoindia/settings/base.py
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> HOTFIX - remove whitenoise

- frontend/package-lock.json
- frontend/src/sections/JoinCommunity/JoinCommunity.tsx
- frontend/src/sections/WhatIsDjango/WhatIsDjango.tsx
- frontend/tailwind.config.ts
Fixed issue no. 66 having the responsiveness bug where the screen was breaking on mobile screens
Changes on WhatIsDjango and JoinCommunity files , the issue was with images that were taking extra widths correspodingly and the alignment of the absolute components in css.
I have made the social icons of mobile component as flex wrap, if you want it to get changed please reply, i can do that too.
So, on some screen sizes it'll be 3icons in one row and 1 icon in between
Tested on different screen sizes
> Fixed #66 -- Solved the responsive UI related bug in the home page.

- CODEOWNERS
Updating code owners for backend and frontend for auto reviewer attachment
> Updated code owners for backend and frontend for auto reviewer attachment

- .github/workflows/new_contributor_pr.yml
> Fixed #95 -- Added new contributor message

- contributing.md
- docker-compose.yml
This PR updates the Docker volume configuration to enable live reloading in the frontend, improving the development experience.
- Updated Docker volume configuration to support live reloading in the frontend.
- Review impact on existing Docker workflows.
- Ensure compatibility with current development setup.
- N/A (No visual changes, configuration update only.)
- Tested live reloading in the development environment.
- Ensured Docker container builds and runs correctly.
This update builds upon previous work related to Docker volume configurations for live reloading.
> Update volume configuration for frontend in Docker setup

- backend/djangoindia/db/admin.py
> Fixed #84 -- Added searching, sorting and filtering in admin panel.

- frontend/src/sections/Hero/Hero.tsx
- frontend/src/sections/WhatIsDjango/WhatIsDjango.tsx
- <ONE> Improved Articulation On Landing
- <TWO> Emphasis on India Yet Global Outlook is `Key`
- <ONE> Locally
> Refactored Hero and WhatIsDjango section content

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/DataCard/datacard.tsx
- frontend/src/sections/WhatIsDjango/WhatIsDjango.tsx
- <ONE> `react-intersection-observer` module added
- <TWO> used `react-intersection-observer` to add counter to `WhatIsDjango` component`
- <ONE>
- <ONE> Locally
> Added Counter component to whatisdjango section

- frontend/src/components/DataCard/datacard.tsx
- frontend/src/sections/Goals/Goals.tsx
- frontend/src/sections/WhatIsDjango/WhatIsDjango.tsx
- <ONE> Hover Effect and Dead White Space Covered With Cards
- <ONE>
- <ONE> Locally
> Added hover effect on cards in goal section

- .env.example
- frontend/src/utils/apiUrl.ts
- frontend/src/utils/fetchData.ts
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Fix bug on events API

- backend/djangoindia/settings/production.py
- frontend/src/containers/ContactUs/ContactUs.tsx
- frontend/src/sections/Latestupdate/LatestUpdate.tsx
This is going to need some modifications in frontend as well. Create a branch from this PR's branch and Copy the settings added in this PR from production.py and paste it to local.py to test throttling on local. Then run the backend using docker and show too many requests error message on frontend on all api endpoints.
Before pushing frontend changes remove the settings that were added to local.py. Create a PR from your branch to the branch of this PR.
> Added API throttling policy

- backend/djangoindia/settings/production.py
Reverts djangoindia/djangoindia.org#144
> Revert "Minor change to prod"

- .env.example
- contributing.md
In this PR, I have updated the example env and the contributing MD for updating the doc.
> Added NEXT_PUBLIC_FRONTEND_URL in docs

- backend/djangoindia/bg_tasks/event_registration.py
- backend/templates/admin/registration_success.html
- frontend/src/app/globals.css
- frontend/src/containers/Event/Event.tsx
- frontend/src/containers/RegisterEvent/RegisterEvent.tsx
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Event registration form bugs fixed

- contributing.md
- contributions.md
Since hacktoberfest starts tomorrow: https://hacktoberfest.com/
> Added details for low or no code contributions

- frontend/src/containers/Event/Event.tsx
- frontend/src/containers/RegisterEvent/RegisterEvent.tsx
- frontend/src/sections/EventSection/EventCard.tsx
- frontend/src/sections/EventSection/Main.tsx
- frontend/src/utils/dayjsWithTZ.ts
- frontend/src/utils/index.ts
> Created reusable timezone util for converting all the times

- backend/djangoindia/api/serializers/event.py
- backend/djangoindia/api/urls/event.py
- backend/djangoindia/api/views/event.py
- backend/djangoindia/bg_tasks/event_registration.py
- backend/djangoindia/db/admin.py
- backend/djangoindia/settings/base.py
- backend/templates/admin/registration_success.html
- frontend/src/sections/CommunityPartners/CommunityPartners.tsx
- mail template fix
- partners logo url fix
- mail timezone fix
> Hotfixes staging

- backend/templates/admin/registration_success.html
- frontend/src/sections/EventVolunteers/EventVolunteers.tsx
mail template and event volunteer pic fixed
> Fix 5 Staging PR - Oct 6,2024

- contributions.md
- Designed user interface for media section
> Created Media Library API design

- contributions.md
Created an attendees list - grid view
Updated the Events Page with attendees list
- [✔] Feature update
- [✔ ] Changes generate no new warnings
- [ ✔] Merging to `main` from `fork:sriyamukkavilli`
> Added Attendees List Figma Link

- contributions.md
- [✔ ] Feature update
- [ ✔] Changes generate no new warnings
> Mandala Illustration kit UI design.

- contributions.md
UI Design and Prototype for the Login/Signup screens
- [✔] Feature update
- [✔] Changes generate no new warnings
- [✔] Documentation has been extended, if necessary
Design and Prototype for member login and signup pages
> New Login and signup page designs

- contributions.md
Design for new sub-hero header for events page
-showcase recent events
-create visually appealing format 
- [✔] Feature update
> added a sub hero header for events page

- frontend/src/sections/Navbar/Navbar.tsx
Make top django logo clickable. 
- [x ] Feature update
- [ x] Code has been commented, particularly in hard-to-understand areas 
- [ x] Changes generate no new warnings
- [ x] Vital changes have been captured in unit and/or integration tests
- [ x] New and existing unit tests pass locally with my changes
- [x ] Documentation has been extended, if necessary
- [x ] Merging to `main` from `fork:Suraj1089/djangoindia.org`
> feat: Make django logo clickable. onClick redirect to homepage

- frontend/src/components/DataCard/DataCard.tsx
Made changes to the UI on website to update the numbers 
Made changes to the DataCard Component 
contributors -> 25 +
subscribers -> 250 +
stars -> 100+
> Updated DataCard numbers on website

- frontend/src/app/(core)/gallery/[slug]/page.tsx
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Image Optimization

- backend/djangoindia/api/views/event.py
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Fixed #212 -- Prevented community partners in past events

- backend/djangoindia/api/views/event.py
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Fixed Community partners being returned with wrong events.

- frontend/src/sections/EventSection/Main.tsx
> Fixed #260 -- Upcoming events not visible in mobile view

- .github/workflows/docker-build-push.yml
- backend/djangoindia/settings/production.py
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Added github workflow to build docker images automatically

- backend/djangoindia/api/views/authentication.py
- backend/djangoindia/bg_tasks/auth/welcome_email_task.py
- backend/templates/admin/registration_success.html
- backend/templates/admin/waitlist_success.html
- backend/templates/admin/welcome_mail.html
- frontend/src/sections/Footer/Footer.tsx
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Added welcome mail

- backend/djangoindia/middleware.py
- backend/djangoindia/settings/local.py
> Added response time logs

- frontend/src/components/Modal/modal.tsx
#325 has been resolved. 
- I modified the React component to display all validation errors below the respective input fields.
- <ONE>
- <TWO>
**Before changes:** 
**After changes:**
- Manual test has been done
- <ONE>
- <TWO>
> Improve error message on subscription

- backend/djangoindia/db/admin.py
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Fixed email sending

- frontend/src/constants/schema.tsx
#341 has been resolved.
This pull request will remove all the errors that are related to the accepted password criteria such as "Password must be at least 8 characters long." , "Password cannot exceed 20 characters." and so on. 
This pull request will not remove the error "Password is required."
- I realized that these errors come from `LOGIN_FORM_SCHEMA`. So, to fix the issue, I removed the errors from the schema. 
- <ONE>
- <TWO>
**Before:**
**After:**
- A manual test has been done
- <ONE>
- <TWO>
> Remove all password criteria errors from Login page

- frontend/src/sections/Navbar/Navbar.tsx
…ad of exiting the website
This PR fixes the issue where the Back button on the Login page would exit the website instead of returning to the homepage. Now, the button correctly returns the user to the homepage.
- Fixed the navigation of the Back button on the Login page.
- Updated the button's functionality to correctly return to the homepage.
- Ensure that the Back button does not affect other navigation functionality.
- Check that the homepage redirection works on all devices.
- Manually tested on Chrome, Firefox, and Safari to ensure consistent behavior.
- Unit tests updated to cover the new button behavior.
- No known conflicts with other navigation components.
> Fix #362 -- Back Button from Login Page Exits Website Instead of Returning to Homepage
